title: "SNUFA"
description: "Spiking Neural networks as Universal Function Approximators"
show_downloads: false
github:
  is_project_page: false
remote_theme: jekyll/minima@v2.5.2
plugins:
- jekyll-remote-theme