title: "SNUFA"
description: "Spiking Neural networks as Universal Function Approximators"
show_downloads: false
github:
  is_project_page: false
remote_theme: jekyll/cayman@0.2.0
plugins:
- jekyll-remote-theme