title: "SNUFA"
description: "Spiking Neural networks as Universal Function Approximators"
show_downloads: false
github:
  is_project_page: false
remote_theme: page-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: "/snufa-website-dev" # comment this out when merging back to main snufa site