title: "SNUFA"
description: "SNUFA"
show_downloads: false
github:
  is_project_page: false
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: "/snufa-website-dev" # comment this out when merging back to main snufa site
meeting_years:
- 2025
- 2024
- 2023
- 2022
- 2021
- 2020